name: wowweddings
favicon: null
layout_spectrum: 0.507575458381325
typography_spectrum: 0.9446504125371575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5685806765686721
  lightness: 0.7977885336149484
  saturation: 0.9060192406177521
  rhythmicContrast: 0.6675044321455061
purpose: []
